## **Weather forecasts**

#### **Data Analysis**

In [2]:
import os
import numpy as np
import pandas as pd

Params

In [ ]:
DATASET = os.path.join("..", "datasets", "weather.csv")

Visualize full dataset

In [4]:
data = pd.read_csv(DATASET)

data.drop(columns=["Unnamed: 0"], inplace=True)

data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,59.0,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No

**DF info & NaN analysis**

Show percentage of NaN values for every feature

In [5]:
print(f"Total number of records: {len(data)}")
print(f"Total number of columns: {len(data.columns)}")
print(f"Total number of locations: {len(data["Location"].unique().tolist())}")

data_stats = pd.DataFrame(data={
    "DType": data.dtypes,
    "NaCount": len(data) - data.T.count(axis=1),
    "NaPct": round(((len(data) - data.T.count(axis=1)) / len(data)) * 100, 1),
    })
data_stats

Total number of records: 142193
Total number of columns: 23
Total number of locations: 49

                 DType  NaCount  NaPct
Date            object        0    0.0
Location        object        0    0.0
MinTemp        float64      637    0.4
MaxTemp        float64      322    0.2
Rainfall       float64     1406    1.0
Evaporation    float64    60843   42.8
Sunshine       float64    67816   47.7
WindGustDir     object     9330    6.6
WindGustSpeed  float64     9270    6.5
WindDir9am      object    10013    7.0
WindDir3pm      object     3778    2.7
WindSpeed9am   float64     1348    0.9
WindSpeed3pm   float64     2630    1.8
Humidity9am    float64     1774    1.2
Humidity3pm    float64     3610    2.5
Pressure9am    float64    14014    9.9
Pressure3pm    float64    13981    9.8
Cloud9am       float64    53657   37.7
Cloud3pm       float64    57094   40.2
Temp9am        float64      904    0.6
Temp3pm        float64     2726    1.9
RainToday       object     1406    1.0
RainTomorrow    object        0    0.0

Show percentage of NaN values for every feature and location

In [6]:
loc_view = data.drop(columns='Location', axis=1).groupby(data['Location']).apply(lambda x: x.isna().sum()/len(x)*100).round(1)
loc_view

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Location,,,,,,,,,,,,,,,,,,,,,
Adelaide,0.0,0.1,0.1,2.3,46.6,45.0,0.7,0.7,8.4,0.5,...,0.2,0.2,0.3,0.2,100.0,100.0,0.2,0.1,2.3,0.0
Albany,0.0,2.0,1.1,0.7,9.3,16.8,100.0,100.0,8.1,25.4,...,1.5,23.2,0.8,0.8,1.2,23.0,1.2,23.1,0.7,0.0
Albury,0.0,0.2,0.0,0.7,100.0,100.0,0.3,0.3,17.2,1.4,...,0.1,0.1,0.0,0.1,57.4,53.0,0.1,0.1,0.7,0.0
AliceSprings,0.0,0.0,0.0,0.2,7.0,16.9,1.6,1.6,7.6,0.1,...,0.1,0.2,0.0,0.1,11.0,11.8,0.0,0.1,0.2,0.0
BadgerysCreek,0.0,0.4,0.1,1.7,100.0,100.0,0.5,0.5,13.5,2.0,...,1.0,1.1,4.9,5.1,100.0,100.0,0.5,0.7,1.7,0.0
Ballarat,0.0,0.0,0.0,0.4,100.0,100.0,0.8,0.8,3.0,0.5,...,0.7,0.2,0.8,0.8,18.0,34.4,0.4,0.2,0.4,0.0
Bendigo,0.0,0.0,0.0,0.1,60.9,100.0,1.2,1.2,8.0,1.4,...,0.2,0.0,0.5,0.3,31.8,25.3,0.1,0.0,0.1,0.0
Brisbane,0.0,0.2,0.1,0.9,0.6,1.5,0.5,0.5,2.2,0.9,...,0.1,0.3,0.0,0.1,0.0,0.1,0.1,0.3,0.9,0.0
Cairns,0.0,0.0,0.0,0.8,11.4,14.3,0.6,0.6,1.4,0.1,...,0.0,0.0,0.0,0.0,6.2,6.9,0.0,0.0,0.8,0.0
Canberra,0.0,0.1,0.1,0.5,46.7,55.8,9.6,9.6,15.7,6.7,...,1.8,0.4,6.6,6.4,31.2,36.7,0.5,0.2,0.5,0.0
Cobar,0.0,0.1,0.0,0.3,11.0,81.6,1.3,1.3,0.8,0.5,...,3.8,3.8,0.9,0.8,12.3,10.1,0.2,0.2,0.3,0.0
CoffsHarbour,0.0,0.1,0.2,0.4,39.7,49.5,10.6,10.6,10.2,8.7,...,0.2,0.4,9.0,9.0,25.9,24.8,0.1,0.1,0.4,0.0
Dartmoor,0.0,0.2,0.0,0.1,13.9,15.0,0.1,0.1,17.2,1.2,...,5.6,5.5,0.0,0.1,100.0,100.0,0.1,0.0,0.1,0.0
Darwin,0.0,0.0,0.0,0.0,1.7,0.1,1.4,1.3,0.9,0.1,...,0.0,0.1,0.0,0.1,0.0,0.1,0.0,0.1,0.0,0.0
GoldCoast,0.0,0.0,0.0,1.9,100.0,100.0,2.9,2.9,2.0,1.1,...,0.3,0.3,0.0,0.0,100.0,100.0,0.0,0.0,1.9,0.0
Hobart,0.0,0.0,0.0,0.2,0.2,0.4,0.6,0.6,1.3,0.6,...,0.3,0.4,0.0,0.0,36.4,36.6,0.0,0.1,0.2,0.0
Katherine,0.0,2.8,1.4,0.9,5.5,100.0,1.8,1.8,2.6,1.2,...,4.9,52.7,0.1,0.3,2.4,45.5,2.4,45.5,0.9,0.0
Launceston,0.0,0.1,0.1,0.3,95.3,100.0,1.0,1.0,15.1,1.8,...,0.1,0.2,37.8,37.8,76.2,75.7,0.1,0.2,0.3,0.0
Melbourne,0.0,0.0,0.0,5.6,0.0,0.0,0.6,0.6,1.6,0.5,...,0.1,0.3,0.0,0.1,16.7,19.2,0.1,0.2,5.6,0.0
MelbourneAirport,0.0,0.0,0.0,0.0,0.1,0.0,0.5,0.5,1.3,0.4,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Mildura,0.0,0.0,0.0,0.1,3.9,4.4,0.1,0.1,3.1,0.3,...,0.1,0.1,0.1,0.1,2.8,4.9,0.0,0.0,0.1,0.0
Moree,0.0,0.1,0.0,2.2,21.7,28.1,2.6,2.5,3.7,1.8,...,0.1,0.2,0.0,0.0,16.9,12.8,0.0,0.0,2.2,0.0
MountGambier,0.0,0.0,0.0,0.3,13.2,14.3,1.5,1.4,2.7,0.6,...,0.4,0.3,0.0,0.2,3.5,3.6,0.0,0.2,0.3,0.0
MountGinini,0.0,2.0,0.5,3.1,100.0,100.0,6.6,6.6,6.8,6.1,...,13.0,8.6,100.0,100.0,100.0,100.0,12.5,8.0,3.1,0.0
Newcastle,0.0,9.7,5.4,0.9,100.0,100.0,100.0,100.0,45.8,42.0,...,6.1,29.3,100.0,100.0,6.1,29.1,5.9,29.1,0.9,0.0
Nhil,0.0,0.0,0.0,0.3,100.0,100.0,0.1,0.1,2.9,0.0,...,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,0.3,0.0
NorahHead,0.0,0.3,0.2,1.4,100.0,100.0,0.1,0.1,2.9,1.0,...,0.6,0.5,0.4,0.3,100.0,100.0,0.6,0.4,1.4,0.0
NorfolkIsland,0.0,0.0,0.0,0.7,7.0,13.3,1.5,1.4,1.0,0.2,...,0.2,0.1,0.3,0.1,2.1,2.0,0.2,0.1,0.7,0.0
Nuriootpa,0.0,0.4,0.2,0.2,4.1,5.2,1.5,1.0,4.8,1.1,...,0.3,0.4,0.2,0.3,4.2,25.5,0.2,0.2,0.2,0.0
PearceRAAF,0.0,0.8,0.6,4.2,100.0,0.2,3.9,3.9,3.0,0.9,...,0.6,0.9,0.7,0.9,34.3,37.2,0.5,0.8,4.2,0.0
Penrith,0.0,0.3,0.0,1.8,100.0,100.0,0.2,0.2,17.9,2.0,...,2.5,2.0,100.0,100.0,100.0,100.0,0.6,0.3,1.8,0.0
Perth,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.2,4.2,0.2,...,0.3,0.3,0.0,0.0,0.1,0.1,0.0,0.0,0.0,0.0
PerthAirport,0.0,0.0,0.0,0.0,0.0,0.2,1.5,1.5,1.3,0.0,...,0.0,0.0,0.1,0.0,0.1,0.1,0.0,0.0,0.0,0.0
Portland,0.0,0.3,0.0,0.4,13.6,14.7,0.8,0.8,2.3,0.2,...,1.6,0.4,0.4,0.3,13.7,17.3,1.6,0.4,0.4,0.0
Richmond,0.0,0.4,0.2,1.5,45.9,100.0,0.6,0.5,27.9,3.4,...,1.6,1.6,0.7,0.8,79.6,80.3,1.0,0.9,1.5,0.0
Sale,0.0,0.0,0.0,0.3,38.9,39.4,4.5,4.5,2.7,0.5,...,0.6,0.5,0.5,0.5,11.8,12.9,0.1,0.0,0.3,0.0
SalmonGums,0.0,0.2,0.1,0.5,100.0,100.0,1.6,1.6,2.2,1.5,...,0.1,0.1,100.0,100.0,100.0,100.0,0.1,0.1,0.5,0.0
Sydney,0.0,0.1,0.1,0.2,1.5,0.5,31.0,31.0,1.7,1.0,...,0.4,0.4,0.6,0.6,17.0,16.8,0.1,0.1,0.2,0.0
SydneyAirport,0.0,0.0,0.0,0.1,1.5,0.5,1.7,1.7,0.3,0.1,...,0.1,0.1,0.3,0.1,0.1,0.0,0.0,0.0,0.1,0.0
Townsville,0.0,0.1,0.0,0.2,2.9,13.7,0.7,0.7,4.1,0.0,...,0.0,0.0,0.0,0.0,5.7,9.0,0.0,0.0,0.2,0.0
Tuggeranong,0.0,0.0,0.0,1.3,100.0,100.0,0.4,0.4,21.1,1.5,...,0.7,0.4,0.5,0.3,100.0,100.0,0.7,0.4,1.3,0.0
Uluru,0.0,0.2,0.0,1.2,100.0,100.0,1.7,1.7,3.6,1.8,...,0.2,0.1,0.2,0.1,77.8,73.2,0.2,0.1,1.2,0.0
WaggaWagga,0.0,0.0,0.0,0.6,4.1,13.5,0.9,0.9,4.0,0.5,...,0.1,0.0,0.0,0.0,7.0,5.3,0.0,0.0,0.6,0.0
Walpole,0.0,0.4,0.2,1.7,100.0,100.0,2.3,1.2,8.7,2.0,...,1.2,1.2,0.1,0.1,100.0,100.0,0.1,0.1,1.7,0.0
Watsonia,0.0,0.2,0.0,0.3,0.1,0.0,1.1,1.1,6.3,1.2,...,0.4,0.0,0.0,0.0,0.0,0.0,0.4,0.0,0.3,0.0
Williamtown,0.0,0.0,0.1,6.9,30.0,47.1,4.6,4.6,2.9,0.6,...,0.3,0.3,0.4,0.4,17.9,20.0,0.2,0.1,6.9,0.0
Witchcliffe,0.0,0.3,0.2,0.9,100.0,100.0,0.5,0.5,8.4,0.6,...,8.1,7.9,4.5,4.5,100.0,100.0,0.1,0.0,0.9,0.0
Wollongong,0.0,0.4,0.1,1.3,100.0,100.0,0.3,0.3,4.0,1.0,...,0.7,0.6,1.7,0.6,55.7,53.1,0.7,0.6,1.3,0.0
Woomera,0.0,0.1,0.1,0.2,14.2,33.0,1.3,1.3,1.0,0.6,...,0.4,0.9,0.4,0.5,12.1,21.8,0.0,0.1,0.2,0.0

Add to DF info

In [7]:
data_stats["LocsWhere>30%NA"] = loc_view.T.where(loc_view.T >= 30, np.nan).count(axis=1)
data_stats["LocsWhere100%NA"] = loc_view.T.where(loc_view.T == 100, np.nan).count(axis=1)
data_stats["LocsWhere>30%NA"] = data_stats["LocsWhere>30%NA"].fillna(0).astype(int)
data_stats["LocsWhere100%NA"] = data_stats["LocsWhere100%NA"].fillna(0).astype(int)
data_stats

                 DType  NaCount  NaPct  LocsWhere>30%NA  LocsWhere100%NA
Date            object        0    0.0                0                0
Location        object        0    0.0                0                0
MinTemp        float64      637    0.4                0                0
MaxTemp        float64      322    0.2                0                0
Rainfall       float64     1406    1.0                0                0
Evaporation    float64    60843   42.8               24               16
Sunshine       float64    67816   47.7               26               19
WindGustDir     object     9330    6.6                3                2
WindGustSpeed  float64     9270    6.5                3                2
WindDir9am      object    10013    7.0                1                0
WindDir3pm      object     3778    2.7                1                0
WindSpeed9am   float64     1348    0.9                0                0
WindSpeed3pm   float64     2630    1.8                0                0
Humidity9am    float64     1774    1.2                0                0
Humidity3pm    float64     3610    2.5                1                0
Pressure9am    float64    14014    9.9                5                4
Pressure3pm    float64    13981    9.8                5                4
Cloud9am       float64    53657   37.7               21               12
Cloud3pm       float64    57094   40.2               22               12
Temp9am        float64      904    0.6                0                0
Temp3pm        float64     2726    1.9                1                0
RainToday       object     1406    1.0                0                0
RainTomorrow    object        0    0.0                0                0

Show what are the locations with more than 30% NaN values

In [8]:
na_feats = data_stats[data_stats["NaPct"] > 30]
na_feats

               DType  NaCount  NaPct  LocsWhere>30%NA  LocsWhere100%NA
Evaporation  float64    60843   42.8               24               16
Sunshine     float64    67816   47.7               26               19
Cloud9am     float64    53657   37.7               21               12
Cloud3pm     float64    57094   40.2               22               12

In [9]:
na_locs = []
for feat in na_feats.index:
    locs = loc_view[loc_view[feat] == 100].index.tolist()
    na_locs += locs
    print(f"{len(locs)}: {locs}")

16: ['Albury', 'BadgerysCreek', 'Ballarat', 'GoldCoast', 'MountGinini', 'Newcastle', 'Nhil', 'NorahHead', 'PearceRAAF', 'Penrith', 'SalmonGums', 'Tuggeranong', 'Uluru', 'Walpole', 'Witchcliffe', 'Wollongong']
19: ['Albury', 'BadgerysCreek', 'Ballarat', 'Bendigo', 'GoldCoast', 'Katherine', 'Launceston', 'MountGinini', 'Newcastle', 'Nhil', 'NorahHead', 'Penrith', 'Richmond', 'SalmonGums', 'Tuggeranong', 'Uluru', 'Walpole', 'Witchcliffe', 'Wollongong']
12: ['Adelaide', 'BadgerysCreek', 'Dartmoor', 'GoldCoast', 'MountGinini', 'Nhil', 'NorahHead', 'Penrith', 'SalmonGums', 'Tuggeranong', 'Walpole', 'Witchcliffe']
12: ['Adelaide', 'BadgerysCreek', 'Dartmoor', 'GoldCoast', 'MountGinini', 'Nhil', 'NorahHead', 'Penrith', 'SalmonGums', 'Tuggeranong', 'Walpole', 'Witchcliffe']

In [10]:
all_na_locs = set(na_locs)
print(f"Total locations with more than 30% NaN values: {len(all_na_locs)} / {len(data['Location'].unique().tolist())}")
all_na_locs

Total locations with more than 30% NaN values: 22 / 49

{'Adelaide',
 'Albury',
 'BadgerysCreek',
 'Ballarat',
 'Bendigo',
 'Dartmoor',
 'GoldCoast',
 'Katherine',
 'Launceston',
 'MountGinini',
 'Newcastle',
 'Nhil',
 'NorahHead',
 'PearceRAAF',
 'Penrith',
 'Richmond',
 'SalmonGums',
 'Tuggeranong',
 'Uluru',
 'Walpole',
 'Witchcliffe',
 'Wollongong'}

**Recap**

For 4 features out of the 23 columns, I have 22 locations out of 49 with more than 30% NaN data.

Since data are daily and highly variable, using interpolation through an Imputer would not make sense (I made an experiment anyway in the notebook "DecTree_imputer.ipynb"). Therefore, filling the gaps in the dataset would require to train a predictive model on the remaining data anyway.

I have two choices to clean the dataset:

* A) drop all rows with NaN, thus renouncing at data from these 22 locations and sparse missing values (note: temporal info is not needed in this dataset);
* B) drop the 4 features first, and then drop all rows with NaN.

Considering that the majority of NaN are concentrated in these 4 columns and that the 22 locations identified have enough data for all the remaining features, option B should be preferred.

To have an idea of the impact in terms of data loss:

In [11]:
# OPTION A)
data_a = data.dropna().reset_index(drop=True)
print(f"Option A) Keep {len(data_a.index)} records out of {len(data.index)} ({round((len(data_a.index) / len(data.index))*100, 1)}%)")

Option A) Keep 56420 records out of 142193 (39.7%)

In [18]:
# OPTION B)
data_b = data.drop(columns=na_feats.index).dropna().reset_index(drop=True)
print(f"Option B) Keep {len(data_b.index)} records out of {len(data.index)} ({round((len(data_b.index) / len(data.index))*100, 1)}%)")

Option B) Keep 112925 records out of 142193 (79.4%)

Definitely, option B is preferred.

**Basic data analysis**

In [19]:
data_b.describe()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
count,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000,112925.000000
mean,12.664721,23.655670,2.377892,40.786611,15.179163,19.500545,67.404162,50.669055,1017.425847,1015.048962,17.462008,22.127306
std,6.254135,6.982702,8.602968,13.321774,8.344304,8.580097,18.911610,20.768550,7.032654,6.957822,6.355045,6.837380
min,-8.200000,2.600000,0.000000,7.000000,2.000000,2.000000,0.000000,0.000000,980.500000,977.100000,-3.100000,1.700000
25%,8.100000,18.300000,0.000000,31.000000,9.000000,13.000000,56.000000,36.000000,1012.800000,1010.300000,12.700000,16.900000
50%,12.400000,23.100000,0.000000,39.000000,13.000000,19.000000,68.000000,51.000000,1017.400000,1015.000000,17.100000,21.600000
75%,17.200000,28.700000,0.800000,48.000000,20.000000,24.000000,81.000000,65.000000,1022.100000,1019.700000,22.000000,26.900000
max,33.900000,48.100000,367.600000,135.000000,87.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,40.200000,46.700000

Basic check on RainToday column: through a quick look at the data via DataWrangler, I get the impression that the 2 columns are redundant. Checking if the first impression is true:

In [20]:
rain_df = data_b[["Rainfall", "RainToday"]]
rain_df

        Rainfall RainToday
0            0.6        No
1            0.0        No
2            0.0        No
3            0.0        No
4            1.0        No
...          ...       ...
112920       0.0        No
112921       0.0        No
112922       0.0        No
112923       0.0        No
112924       0.0        No

[112925 rows x 2 columns]

In [21]:
rainfall_agg = np.where(rain_df["Rainfall"] > 1, 1, 0)
raintoday = np.where(rain_df["RainToday"] == "Yes", 1, 0)

np.array_equal(rainfall_agg, raintoday)

True